sudo: false
language: java
jdk:
  - oraclejdk8

install: true
script: ./gradlew build publishPlugin

before_cache:
  - rm -f #HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email: false